Repository hashicorp/terraform-provider-local, pull requests merged in 2022-03, with the labels that each got.

#101 Add sensitive option to local_file to suppress output in plan
  internal/provider/data_source_local_file.go
  internal/provider/data_source_local_file_test.go
  website/docs/d/file.html.md
Labels: documentation, size/M

#107 GH Action to link incoming issues and pull-requests to the Terraform DevEx Team board
  .github/workflows/add-content-to-project.yml
Labels: size/S

#108 Update GH Action 'add-content-to-project' to use 'pull_request_target' to allow access to project secrets
  .github/workflows/add-content-to-project.yml
Labels: size/XS

#109 Temporarily disable publishing of `terraform-registry-manifest.json`
  .goreleaser.yml
Labels: size/XS

#112 Update CODEOWNERS with new team name: @hashicorp/terraform-devex
  .github/CODEOWNERS
Labels: size/XS

#115 Add hc-releases upload-file -upload-name flag to goreleaser configuration
  .goreleaser.yml
Labels: size/XS
