Repository hashicorp/terraform-provider-local, pull requests merged in 2023-03, with the labels that each got.

#181 Update release workflow to use service account PAT
  .github/workflows/release.yml
Labels: size/S

#184 Updating to Go 1.19
  .changes/unreleased/NOTES-20230303-160703.yaml
  .github/workflows/test.yml
  README.md
  go.mod
Labels: dependencies, size/XS, go

#186 .github/workflows: Test on Terraform 1.4.* versions
  .github/workflows/test.yml
Labels: size/XS

#187 Migrate acceptance tests to terraform-plugin-testing
  go.mod
  go.sum
  internal/provider/data_source_local_file_test.go
  internal/provider/data_source_local_sensitive_file_test.go
  internal/provider/provider_test.go
  internal/provider/resource_local_file_test.go
  internal/provider/resource_local_sensitive_file_test.go
Labels: dependencies, size/XS, technical-debt
