Repository hashicorp/terraform-provider-local, pull requests merged in 2023-08, with the labels that each got.

#232 Adding Terraform 1.5.* to test matrix
  .github/workflows/test.yml
Labels: enhancement, size/XS

#239 cdktf: update documentation
  docs/cdktf/python/data-sources/file.md
  docs/cdktf/python/data-sources/sensitive_file.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/file.md
  docs/cdktf/python/resources/sensitive_file.md
  docs/cdktf/typescript/data-sources/file.md
  docs/cdktf/typescript/data-sources/sensitive_file.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/file.md
  docs/cdktf/typescript/resources/sensitive_file.md
Labels: size/M

#241 cdktf: update documentation
  docs/cdktf/python/data-sources/file.md
  docs/cdktf/python/data-sources/sensitive_file.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/file.md
  docs/cdktf/python/resources/sensitive_file.md
  docs/cdktf/typescript/data-sources/file.md
  docs/cdktf/typescript/data-sources/sensitive_file.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/file.md
  docs/cdktf/typescript/resources/sensitive_file.md
Labels: size/S
