Repository hashicorp/terraform-provider-local, pull requests merged in 2024-03, with the labels that each got.

#285 `function/direxists`: Add function that checks if a directory exists
  .changes/unreleased/FEATURES-20240116-180627.yaml
  .github/workflows/test.yml
  docs/functions/direxists.md
  examples/functions/direxists/basic.tf
  examples/functions/direxists/example-directory/.gitkeep
  examples/functions/direxists/homedir.tf
  go.mod
  internal/provider/data_source_local_file_test.go
  internal/provider/data_source_local_sensitive_file_test.go
  internal/provider/function_direxists.go
  internal/provider/function_direxists_test.go
  internal/provider/provider.go
  internal/provider/testdata/TestDirectoryExists_basic/main.tf
  internal/provider/testdata/TestDirectoryExists_basic/test_dir/.gitkeep
  internal/provider/testdata/TestDirectoryExists_invalid_file/main.tf
  internal/provider/testdata/TestDirectoryExists_invalid_file/not_a_dir.txt
  internal/provider/testdata/TestDirectoryExists_invalid_symlink/main.tf
  internal/provider/testdata/TestDirectoryExists_invalid_symlink/not_a_dir_symlink
  internal/provider/testdata/TestDirectoryExists_invalid_symlink/test_dir/not_a_dir.txt
  internal/provider/testdata/TestLocalFileDataSource/local_file
  internal/provider/testdata/TestLocalFileDataSource/main.tf
  internal/provider/testdata/TestLocalFileSensitiveDataSource/local_file
  internal/provider/testdata/TestLocalFileSensitiveDataSource/main.tf
  templates/functions/direxists.md.tmpl
Labels: enhancement, dependencies, size/XL

#303 docs: Fix YAML frontmatter in template
  .changes/unreleased/NOTES-20240311-150450.yaml
  docs/functions/direxists.md
  templates/functions/direxists.md.tmpl
Labels: documentation, size/XS

#305 cdktf: update documentation
  docs/cdktf/python/functions/direxists.md
  docs/cdktf/typescript/functions/direxists.md
Labels: size/M
