Repository hashicorp/terraform-provider-local, pull requests merged in 2024-01, with the labels that each got.

#281 cdktf: update documentation
  docs/cdktf/python/data-sources/file.md
  docs/cdktf/python/data-sources/sensitive_file.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/file.md
  docs/cdktf/python/resources/sensitive_file.md
  docs/cdktf/typescript/data-sources/file.md
  docs/cdktf/typescript/data-sources/sensitive_file.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/file.md
  docs/cdktf/typescript/resources/sensitive_file.md
Labels: size/S

#282 Add `issues: write` permission to release workflow to close associated GitHub milestone
  .github/workflows/release.yml
Labels: size/XS

#286 cdktf: update documentation
  docs/cdktf/python/data-sources/file.md
  docs/cdktf/python/data-sources/sensitive_file.md
  docs/cdktf/python/index.md
  docs/cdktf/python/resources/file.md
  docs/cdktf/python/resources/sensitive_file.md
  docs/cdktf/typescript/data-sources/file.md
  docs/cdktf/typescript/data-sources/sensitive_file.md
  docs/cdktf/typescript/index.md
  docs/cdktf/typescript/resources/file.md
  docs/cdktf/typescript/resources/sensitive_file.md
Labels: size/XS

#289 .github/workflows: Update to hashicorp/ghaction-terraform-provider-release@v3
  .github/workflows/release.yml
Labels: size/XS

#293 Added GHA dependabot config for managing hashicorp actions
  .github/dependabot.yml
Labels: dependencies, size/XS
