Repository hashicorp/terraform-provider-local, pull requests merged in 2025-05, with the labels that each got.

#413 Prepare for v2.5.3 release
  .changes/2.5.3.md
  CHANGELOG.md
  README.md
  version/VERSION
Labels: size/XS

#415 chore: Final CRT onboarding
  .copywrite.hcl
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/L

#416 Add catalog metadata (META.d)
  .copywrite.hcl
  META.d/_summary.yaml
Labels: size/XS

#418 github: Use Dependabot to keep Actions updated
  .github/dependabot.yml
Labels: dependencies, size/XS

#422 Create pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS
